/*
 * Basis Theory API
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.basistheory;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdatePrivacy
 */
public class UpdatePrivacyTest {
    private final UpdatePrivacy model = new UpdatePrivacy();

    /**
     * Model tests for UpdatePrivacy
     */
    @Test
    public void testUpdatePrivacy() {
        // TODO: test UpdatePrivacy
    }

    /**
     * Test the property 'impactLevel'
     */
    @Test
    public void impactLevelTest() {
        // TODO: test impactLevel
    }

    /**
     * Test the property 'restrictionPolicy'
     */
    @Test
    public void restrictionPolicyTest() {
        // TODO: test restrictionPolicy
    }

}
