/*
 * Basis Theory API
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.basistheory;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.basistheory.JSON;

/**
 * Privacy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Privacy {
  public static final String SERIALIZED_NAME_CLASSIFICATION = "classification";
  @SerializedName(SERIALIZED_NAME_CLASSIFICATION)
  private String classification;

  public static final String SERIALIZED_NAME_IMPACT_LEVEL = "impact_level";
  @SerializedName(SERIALIZED_NAME_IMPACT_LEVEL)
  private String impactLevel;

  public static final String SERIALIZED_NAME_RESTRICTION_POLICY = "restriction_policy";
  @SerializedName(SERIALIZED_NAME_RESTRICTION_POLICY)
  private String restrictionPolicy;

  public Privacy() {
  }

  public Privacy classification(String classification) {
    
    this.classification = classification;
    return this;
  }

   /**
   * Get classification
   * @return classification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClassification() {
    return classification;
  }


  public void setClassification(String classification) {
    this.classification = classification;
  }


  public Privacy impactLevel(String impactLevel) {
    
    this.impactLevel = impactLevel;
    return this;
  }

   /**
   * Get impactLevel
   * @return impactLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImpactLevel() {
    return impactLevel;
  }


  public void setImpactLevel(String impactLevel) {
    this.impactLevel = impactLevel;
  }


  public Privacy restrictionPolicy(String restrictionPolicy) {
    
    this.restrictionPolicy = restrictionPolicy;
    return this;
  }

   /**
   * Get restrictionPolicy
   * @return restrictionPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRestrictionPolicy() {
    return restrictionPolicy;
  }


  public void setRestrictionPolicy(String restrictionPolicy) {
    this.restrictionPolicy = restrictionPolicy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Privacy privacy = (Privacy) o;
    return Objects.equals(this.classification, privacy.classification) &&
        Objects.equals(this.impactLevel, privacy.impactLevel) &&
        Objects.equals(this.restrictionPolicy, privacy.restrictionPolicy);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(classification, impactLevel, restrictionPolicy);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Privacy {\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    impactLevel: ").append(toIndentedString(impactLevel)).append("\n");
    sb.append("    restrictionPolicy: ").append(toIndentedString(restrictionPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("classification");
    openapiFields.add("impact_level");
    openapiFields.add("restriction_policy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Privacy
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Privacy.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Privacy is not found in the empty JSON string", Privacy.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Privacy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Privacy` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("classification") != null && !jsonObj.get("classification").isJsonNull()) && !jsonObj.get("classification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `classification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("classification").toString()));
      }
      if ((jsonObj.get("impact_level") != null && !jsonObj.get("impact_level").isJsonNull()) && !jsonObj.get("impact_level").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `impact_level` to be a primitive type in the JSON string but got `%s`", jsonObj.get("impact_level").toString()));
      }
      if ((jsonObj.get("restriction_policy") != null && !jsonObj.get("restriction_policy").isJsonNull()) && !jsonObj.get("restriction_policy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `restriction_policy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("restriction_policy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Privacy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Privacy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Privacy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Privacy.class));

       return (TypeAdapter<T>) new TypeAdapter<Privacy>() {
           @Override
           public void write(JsonWriter out, Privacy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Privacy read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Privacy given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Privacy
  * @throws IOException if the JSON string is invalid with respect to Privacy
  */
  public static Privacy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Privacy.class);
  }

 /**
  * Convert an instance of Privacy to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

