/*
 * Basis Theory API
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.basistheory;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TenantInvitationStatus
 */
@JsonAdapter(TenantInvitationStatus.Adapter.class)
public enum TenantInvitationStatus {
  
  PENDING("PENDING"),
  
  EXPIRED("EXPIRED");

  private String value;

  TenantInvitationStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TenantInvitationStatus fromValue(String value) {
    for (TenantInvitationStatus b : TenantInvitationStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TenantInvitationStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final TenantInvitationStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TenantInvitationStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TenantInvitationStatus.fromValue(value);
    }
  }
}

