/*
 * Basis Theory API
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.basistheory;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.basistheory.JSON;

/**
 * ThreeDSMobileSdkRenderOptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ThreeDSMobileSdkRenderOptions {
  public static final String SERIALIZED_NAME_SDK_INTERFACE = "sdk_interface";
  @SerializedName(SERIALIZED_NAME_SDK_INTERFACE)
  private String sdkInterface;

  public static final String SERIALIZED_NAME_SDK_UI_TYPE = "sdk_ui_type";
  @SerializedName(SERIALIZED_NAME_SDK_UI_TYPE)
  private List<String> sdkUiType = null;

  public ThreeDSMobileSdkRenderOptions() {
  }

  public ThreeDSMobileSdkRenderOptions sdkInterface(String sdkInterface) {
    
    this.sdkInterface = sdkInterface;
    return this;
  }

   /**
   * Get sdkInterface
   * @return sdkInterface
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSdkInterface() {
    return sdkInterface;
  }


  public void setSdkInterface(String sdkInterface) {
    this.sdkInterface = sdkInterface;
  }


  public ThreeDSMobileSdkRenderOptions sdkUiType(List<String> sdkUiType) {
    
    this.sdkUiType = sdkUiType;
    return this;
  }

  public ThreeDSMobileSdkRenderOptions addSdkUiTypeItem(String sdkUiTypeItem) {
    if (this.sdkUiType == null) {
      this.sdkUiType = new ArrayList<>();
    }
    this.sdkUiType.add(sdkUiTypeItem);
    return this;
  }

   /**
   * Get sdkUiType
   * @return sdkUiType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSdkUiType() {
    return sdkUiType;
  }


  public void setSdkUiType(List<String> sdkUiType) {
    this.sdkUiType = sdkUiType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSMobileSdkRenderOptions threeDSMobileSdkRenderOptions = (ThreeDSMobileSdkRenderOptions) o;
    return Objects.equals(this.sdkInterface, threeDSMobileSdkRenderOptions.sdkInterface) &&
        Objects.equals(this.sdkUiType, threeDSMobileSdkRenderOptions.sdkUiType);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sdkInterface, sdkUiType);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSMobileSdkRenderOptions {\n");
    sb.append("    sdkInterface: ").append(toIndentedString(sdkInterface)).append("\n");
    sb.append("    sdkUiType: ").append(toIndentedString(sdkUiType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sdk_interface");
    openapiFields.add("sdk_ui_type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ThreeDSMobileSdkRenderOptions
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ThreeDSMobileSdkRenderOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ThreeDSMobileSdkRenderOptions is not found in the empty JSON string", ThreeDSMobileSdkRenderOptions.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("sdk_interface") != null && !jsonObj.get("sdk_interface").isJsonNull()) && !jsonObj.get("sdk_interface").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sdk_interface` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sdk_interface").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("sdk_ui_type") != null && !jsonObj.get("sdk_ui_type").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `sdk_ui_type` to be an array in the JSON string but got `%s`", jsonObj.get("sdk_ui_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ThreeDSMobileSdkRenderOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ThreeDSMobileSdkRenderOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ThreeDSMobileSdkRenderOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ThreeDSMobileSdkRenderOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<ThreeDSMobileSdkRenderOptions>() {
           @Override
           public void write(JsonWriter out, ThreeDSMobileSdkRenderOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ThreeDSMobileSdkRenderOptions read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ThreeDSMobileSdkRenderOptions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ThreeDSMobileSdkRenderOptions
  * @throws IOException if the JSON string is invalid with respect to ThreeDSMobileSdkRenderOptions
  */
  public static ThreeDSMobileSdkRenderOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ThreeDSMobileSdkRenderOptions.class);
  }

 /**
  * Convert an instance of ThreeDSMobileSdkRenderOptions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

