/*
 * Basis Theory API
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.basistheory;

import java.util.Objects;
import java.util.Arrays;
import com.basistheory.EncryptionMetadata;
import com.basistheory.UpdatePrivacy;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.basistheory.JSON;

/**
 * UpdateTokenRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-16T23:28:50.575331Z[Etc/UTC]")
public class UpdateTokenRequest {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private Object data = null;

  public static final String SERIALIZED_NAME_ENCRYPTION = "encryption";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION)
  private EncryptionMetadata encryption;

  public static final String SERIALIZED_NAME_PRIVACY = "privacy";
  @SerializedName(SERIALIZED_NAME_PRIVACY)
  private UpdatePrivacy privacy;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = null;

  public static final String SERIALIZED_NAME_SEARCH_INDEXES = "search_indexes";
  @SerializedName(SERIALIZED_NAME_SEARCH_INDEXES)
  private List<String> searchIndexes = null;

  public static final String SERIALIZED_NAME_FINGERPRINT_EXPRESSION = "fingerprint_expression";
  @SerializedName(SERIALIZED_NAME_FINGERPRINT_EXPRESSION)
  private String fingerprintExpression;

  public static final String SERIALIZED_NAME_MASK = "mask";
  @SerializedName(SERIALIZED_NAME_MASK)
  private Object mask = null;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  private String expiresAt;

  public static final String SERIALIZED_NAME_DEDUPLICATE_TOKEN = "deduplicate_token";
  @SerializedName(SERIALIZED_NAME_DEDUPLICATE_TOKEN)
  private Boolean deduplicateToken;

  public static final String SERIALIZED_NAME_CONTAINERS = "containers";
  @SerializedName(SERIALIZED_NAME_CONTAINERS)
  private List<String> containers = null;

  public UpdateTokenRequest() {
  }

  public UpdateTokenRequest data(Object data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getData() {
    return data;
  }


  public void setData(Object data) {
    this.data = data;
  }


  public UpdateTokenRequest encryption(EncryptionMetadata encryption) {
    
    this.encryption = encryption;
    return this;
  }

   /**
   * Get encryption
   * @return encryption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EncryptionMetadata getEncryption() {
    return encryption;
  }


  public void setEncryption(EncryptionMetadata encryption) {
    this.encryption = encryption;
  }


  public UpdateTokenRequest privacy(UpdatePrivacy privacy) {
    
    this.privacy = privacy;
    return this;
  }

   /**
   * Get privacy
   * @return privacy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UpdatePrivacy getPrivacy() {
    return privacy;
  }


  public void setPrivacy(UpdatePrivacy privacy) {
    this.privacy = privacy;
  }


  public UpdateTokenRequest metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public UpdateTokenRequest putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public UpdateTokenRequest searchIndexes(List<String> searchIndexes) {
    
    this.searchIndexes = searchIndexes;
    return this;
  }

  public UpdateTokenRequest addSearchIndexesItem(String searchIndexesItem) {
    if (this.searchIndexes == null) {
      this.searchIndexes = new ArrayList<>();
    }
    this.searchIndexes.add(searchIndexesItem);
    return this;
  }

   /**
   * Get searchIndexes
   * @return searchIndexes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSearchIndexes() {
    return searchIndexes;
  }


  public void setSearchIndexes(List<String> searchIndexes) {
    this.searchIndexes = searchIndexes;
  }


  public UpdateTokenRequest fingerprintExpression(String fingerprintExpression) {
    
    this.fingerprintExpression = fingerprintExpression;
    return this;
  }

   /**
   * Get fingerprintExpression
   * @return fingerprintExpression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFingerprintExpression() {
    return fingerprintExpression;
  }


  public void setFingerprintExpression(String fingerprintExpression) {
    this.fingerprintExpression = fingerprintExpression;
  }


  public UpdateTokenRequest mask(Object mask) {
    
    this.mask = mask;
    return this;
  }

   /**
   * Get mask
   * @return mask
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMask() {
    return mask;
  }


  public void setMask(Object mask) {
    this.mask = mask;
  }


  public UpdateTokenRequest expiresAt(String expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExpiresAt() {
    return expiresAt;
  }


  public void setExpiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
  }


  public UpdateTokenRequest deduplicateToken(Boolean deduplicateToken) {
    
    this.deduplicateToken = deduplicateToken;
    return this;
  }

   /**
   * Get deduplicateToken
   * @return deduplicateToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDeduplicateToken() {
    return deduplicateToken;
  }


  public void setDeduplicateToken(Boolean deduplicateToken) {
    this.deduplicateToken = deduplicateToken;
  }


  public UpdateTokenRequest containers(List<String> containers) {
    
    this.containers = containers;
    return this;
  }

  public UpdateTokenRequest addContainersItem(String containersItem) {
    if (this.containers == null) {
      this.containers = new ArrayList<>();
    }
    this.containers.add(containersItem);
    return this;
  }

   /**
   * Get containers
   * @return containers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getContainers() {
    return containers;
  }


  public void setContainers(List<String> containers) {
    this.containers = containers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateTokenRequest updateTokenRequest = (UpdateTokenRequest) o;
    return Objects.equals(this.data, updateTokenRequest.data) &&
        Objects.equals(this.encryption, updateTokenRequest.encryption) &&
        Objects.equals(this.privacy, updateTokenRequest.privacy) &&
        Objects.equals(this.metadata, updateTokenRequest.metadata) &&
        Objects.equals(this.searchIndexes, updateTokenRequest.searchIndexes) &&
        Objects.equals(this.fingerprintExpression, updateTokenRequest.fingerprintExpression) &&
        Objects.equals(this.mask, updateTokenRequest.mask) &&
        Objects.equals(this.expiresAt, updateTokenRequest.expiresAt) &&
        Objects.equals(this.deduplicateToken, updateTokenRequest.deduplicateToken) &&
        Objects.equals(this.containers, updateTokenRequest.containers);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, encryption, privacy, metadata, searchIndexes, fingerprintExpression, mask, expiresAt, deduplicateToken, containers);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTokenRequest {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    encryption: ").append(toIndentedString(encryption)).append("\n");
    sb.append("    privacy: ").append(toIndentedString(privacy)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    searchIndexes: ").append(toIndentedString(searchIndexes)).append("\n");
    sb.append("    fingerprintExpression: ").append(toIndentedString(fingerprintExpression)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    deduplicateToken: ").append(toIndentedString(deduplicateToken)).append("\n");
    sb.append("    containers: ").append(toIndentedString(containers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("data");
    openapiFields.add("encryption");
    openapiFields.add("privacy");
    openapiFields.add("metadata");
    openapiFields.add("search_indexes");
    openapiFields.add("fingerprint_expression");
    openapiFields.add("mask");
    openapiFields.add("expires_at");
    openapiFields.add("deduplicate_token");
    openapiFields.add("containers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UpdateTokenRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UpdateTokenRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateTokenRequest is not found in the empty JSON string", UpdateTokenRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!UpdateTokenRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateTokenRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `encryption`
      if (jsonObj.get("encryption") != null && !jsonObj.get("encryption").isJsonNull()) {
        EncryptionMetadata.validateJsonObject(jsonObj.getAsJsonObject("encryption"));
      }
      // validate the optional field `privacy`
      if (jsonObj.get("privacy") != null && !jsonObj.get("privacy").isJsonNull()) {
        UpdatePrivacy.validateJsonObject(jsonObj.getAsJsonObject("privacy"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("search_indexes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `search_indexes` to be an array in the JSON string but got `%s`", jsonObj.get("search_indexes").toString()));
      }
      if ((jsonObj.get("fingerprint_expression") != null && !jsonObj.get("fingerprint_expression").isJsonNull()) && !jsonObj.get("fingerprint_expression").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fingerprint_expression` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fingerprint_expression").toString()));
      }
      if ((jsonObj.get("expires_at") != null && !jsonObj.get("expires_at").isJsonNull()) && !jsonObj.get("expires_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expires_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expires_at").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("containers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `containers` to be an array in the JSON string but got `%s`", jsonObj.get("containers").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateTokenRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateTokenRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateTokenRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateTokenRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateTokenRequest>() {
           @Override
           public void write(JsonWriter out, UpdateTokenRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateTokenRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateTokenRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateTokenRequest
  * @throws IOException if the JSON string is invalid with respect to UpdateTokenRequest
  */
  public static UpdateTokenRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateTokenRequest.class);
  }

 /**
  * Convert an instance of UpdateTokenRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

